### ISSUE TITLE
Issues with validating API keys

### ISSUE THREAD

**Issue by ZandercraftGames** [arkerone/api-key-auth#7]
When I attempt to authenticate with my API using the API key and secret that I have set, it throws the following error no matter what url path I attempt to connect to.
```	<pre>MissingRequiredHeadersError: Missing required HTTP headers : authorization.<br> &nbsp; &nbsp;at Object.parseRequest (C:\Users\ma394545\Desktop\GitHub\beaverworx-api\node_modules\api-key-auth\lib\parser.js:31:13)<br> &nbsp; &nbsp;at middleware (C:\Users\ma394545\Desktop\GitHub\beaverworx-api\node_modules\api-key-auth\lib\index.js:42:32)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\Users\ma394545\Desktop\GitHub\beaverworx-api\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (C:\Users\ma394545\Desktop\GitHub\beaverworx-api\node_modules\express\lib\router\index.js:317:13)<br> &nbsp; &nbsp;at C:\Users\ma394545\Desktop\GitHub\beaverworx-api\node_modules\express\lib\router\index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (C:\Users\ma394545\Desktop\GitHub\beaverworx-api\node_modules\express\lib\router\index.js:335:12)<br> &nbsp; &nbsp;at next (C:\Users\ma394545\Desktop\GitHub\beaverworx-api\node_modules\express\lib\router\index.js:275:10)<br> &nbsp; &nbsp;at jsonParser (C:\Users\ma394545\Desktop\GitHub\beaverworx-api\node_modules\body-parser\lib\types\json.js:110:7)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\Users\ma394545\Desktop\GitHub\beaverworx-api\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (C:\Users\ma394545\Desktop\GitHub\beaverworx-api\node_modules\express\lib\router\index.js:317:13)<br> &nbsp; &nbsp;at C:\Users\ma394545\Desktop\GitHub\beaverworx-api\node_modules\express\lib\router\index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (C:\Users\ma394545\Desktop\GitHub\beaverworx-api\node_modules\express\lib\router\index.js:335:12)<br> &nbsp; &nbsp;at next (C:\Users\ma394545\Desktop\GitHub\beaverworx-api\node_modules\express\lib\router\index.js:275:10)<br> &nbsp; &nbsp;at urlencodedParser (C:\Users\ma394545\Desktop\GitHub\beaverworx-api\node_modules\body-parser\lib\types\urlencoded.js:91:7)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\Users\ma394545\Desktop\GitHub\beaverworx-api\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (C:\Users\ma394545\Desktop\GitHub\beaverworx-api\node_modules\express\lib\router\index.js:317:13)</pre>
```

**Comment by ZandercraftGames** [comment]
Note: Code is available at https://github.com/ZandercraftGames/beaverworx-api

**Comment by arkerone** [comment]
What's the request from the client to your API?

**Comment by ZandercraftGames** [comment]
![image](https://user-images.githubusercontent.com/28664144/74089568-6d5faa00-4a70-11ea-9ce7-63daf1241197.png)
I am new to API creation, so I apologise in advance for my lack of knowledge in the field. 
P.S. The API key and secret are going to be changed before being put into production.

**Comment by arkerone** [comment]
It's not the right way, look the documentation https://github.com/arkerone/api-key-auth/blob/master/signature.md

**Comment by ZandercraftGames** [comment]
I read it, but I dont fully understand it.

**Comment by ZandercraftGames** [comment]
Im not seeing much other than the fact it says I have to use an encrypted signature in either hmac-sha1, hmac-sha256, or hmac-sha512 in the following format:
```
Authorization: Signature keyId="API_KEY",algorithm="hmac-sha256",headers="(request-target) host date digest content-length",signature="Base64(HMAC-SHA256(signing string))"
```

**Comment by ZandercraftGames** [comment]
But how do I create a signature based on the instructions in "Signature creation", and how does it tie into the API key system of the following:
![image](https://user-images.githubusercontent.com/28664144/74090209-c7636e00-4a76-11ea-8785-82a0f1d13413.png)

**Comment by sookoll** [comment]
I'm agree with @ZandercraftGames that documentation is lacking on how to create Authorization header. There is information what it should contain, but how to create one, is missing. @arkerone perhaps You can update documentation with some straightforward guide or example?

**Comment by ZandercraftGames** [comment]
@sookoll Yeah, I literally just gave up and haven't really touched this since my last comment here. I just accepted the fact that I wouldn't get any form of straight-forward help here (at the time of posting). 🤷‍♂

**Comment by arkerone** [comment]
@sookoll The documentation about the creation of the signature is here : https://github.com/arkerone/api-key-auth/blob/master/signature.md 
I describe the part of the authorization header.

@ZandercraftGames You don't use the library properly. You must create the authorization header like the link above and send the header in the "Headers" tab on Postman if you want to test it.
In order you must : 
- Create the signature string,
- Use the algorithm in the following list hmac-sha1, hmac-sha256 or hmac-sha512 to generate a digital signature of the signature string,
- Encode the result of the digital signature in base64.

![image](https://user-images.githubusercontent.com/9639876/78594418-8d310580-7848-11ea-8ab4-0fd4e86df7d9.png)


I think that I will create a client side library to simplify the use of this library.

**Comment by ZandercraftGames** [comment]
@arkerone Thank you for your response. I will try it the way you have described. 😄

**Comment by arkerone** [comment]
@ZandercraftGames It's ok for you?

**Comment by TripTogs** [comment]
can you provide an example of constructing the header?

**Comment by marquitobb** [comment]
![help me please](https://user-images.githubusercontent.com/42453766/87570777-bd314580-c68e-11ea-9806-c65fe7c090ac.png)

**Comment by PanagiotisCY** [comment]
Hi,
Thanks for sharing this package. I am new to nodeJs but this package is straight forward apart from the verify part. Sadly I am getting '**BadSignatureError**' because **verifySignature** is returning false (h1!=h2).

I have created my signature like this:
 **_var signature = crypto.create('hmac-sha256','secret1').update('someText').digest('base64');_**

I modified one section in the parser.js so that i can pass the signature to the X-API-KEY since I will be using Authorization token for oauth2 tokens. The signature looks like this:
**_signature keyid="123456789",algorithm="hmac-sha1",signature="fS+XE0ghVk7EXsPsu7ZsGto6dnqs4lQv9yTeq5dAA2c="_**

I later reinstalled the package and tried the data I found in the apiKeyAuth.test.js but i am getting the same issue. I am not sure what i am doing wrong.

Any help would be much appreciated. Thanks again!

**Comment by PanagiotisCY** [comment]
The answer is here 👍 
https://tools.ietf.org/html/draft-cavage-http-signatures-09#section-1.1

**Comment by the-mcnaveen** [comment]
Facing "MissingRequiredHeadersError: Missing required HTTP headers : authorization."

![image](https://user-images.githubusercontent.com/8493007/93011398-8d7dbb80-f5b3-11ea-9578-e9c60a2c1fdf.png)

**Comment by DannnB** [comment]
This might help give a guide with the Signature process in postman:
I'm only just trying to use this package right now so don't take my code for production.

The comments in the image should explain the process that https://github.com/arkerone/api-key-auth/blob/master/signature.md explains
![image](https://user-images.githubusercontent.com/7425880/112974251-289e4300-914a-11eb-80fe-4d53da5661ab.png)


@arkerone did you get anywhere with the "client-side library"? Is the code above the best practice for using api-key-auth? This would then be moved over to something like Axios. How would you hide the secret on the client app? 

Thanks for any help you can give! I'm new to doing this type of auth for express

Postman "Pre-request script"
```
const apiKey = "847210567175011568915"
const apiSecretKey = "awdoi82th2t9h02t4h0gw0jigq"

const request_settings = {
    method: pm.request.method.toLowerCase(),
    uri: `/${pm.request.url.path.reduce((prevVal, currVal, idx) => idx == 0 ? currVal : prevVal + '/' + currVal, '')}`
}
const signatureRawData = `(request-target): ${request_settings.method} ${request_settings.uri}`
const signature = CryptoJS.enc.Utf8.parse(signatureRawData);

// Create the signature string
const secretByteArray = apiSecretKey;
// Use the algorithm in the following list hmac-sha1, hmac-sha256 or hmac-sha512 to generate a digital signature of the signature string
const signatureBytes = CryptoJS.HmacSHA256(signature,apiSecretKey);
// Encode the result of the digital signature in base64.
const requestSignatureBase64String = CryptoJS.enc.Base64.stringify(signatureBytes);

// create the value for the  "Authorization" header
const signatureValue = `Signature keyId="${apiKey}",algorithm="hmac-sha256",headers="(request-target)",signature="${requestSignatureBase64String}"`

// set it in a environment variable 
pm.environment.set("signature", signatureValue);

// This will show your created "Authorization" header value i nthe postman console
console.log(signatureValue)
```

**Comment by arkerone** [comment]
@DannnB your code looks good ! Unfortunately, I don't have anytime to create a lib for the client side. Don't use it for a "browser" authentication, this auth method must be used only to authenticated a service (server to server). To hide the secret you have severals solutions, you can save the secret on the environment variable or use a service like hashicorp vault or aws secrets manager
